[2018-03-11 20:41:28,276] [ERROR] [command_set] [process:9936] [thread:8284] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058CC250>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-11 20:41:47,284] [ERROR] [host_3] [process:9936] [thread:9344] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058CCA30>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-11 20:43:41,115] [ERROR] [host_3] [process:9936] [thread:9144] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0590B2D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-11 20:45:39,973] [ERROR] [command_set] [process:9936] [thread:8428] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05FD1FF0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-11 20:45:54,694] [ERROR] [command_set] [process:9936] [thread:8520] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05E571D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-11 20:56:25,373] [ERROR] [command_set] [process:9936] [thread:5028] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05A51E70>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-11 20:57:26,625] [ERROR] [command_set] [process:9936] [thread:7608] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05A9D370>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-11 21:00:10,159] [ERROR] [host_3] [process:9936] [thread:5044] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0590BB30>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-11 22:07:07,188] [ERROR] [business_brand] [process:7488] [thread:8032] HTTPConnectionPool(host='172.29.164.92', port=8002): Max retries exceeded with url: /rest/brands/?offset=0&limit=10&is_enabled=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05A0B330>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-11 22:07:47,841] [ERROR] [business_brand] [process:7488] [thread:9660] HTTPConnectionPool(host='172.29.164.92', port=8002): Max retries exceeded with url: /rest/brands/?offset=0&limit=10&is_enabled=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05BA5490>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-11 22:12:13,225] [ERROR] [business_brand] [process:7488] [thread:9536] HTTPConnectionPool(host='172.29.164.92', port=8002): Max retries exceeded with url: /rest/brands/?offset=0&limit=10&is_enabled=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05D172F0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-12 21:57:23,889] [ERROR] [command_set] [process:2616] [thread:6492] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05A977B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-12 21:57:28,773] [ERROR] [host_3] [process:2616] [thread:2232] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05ACC710>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-12 22:09:56,004] [ERROR] [host_1] [process:2616] [thread:2232] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05ACC4D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-12 22:34:39,586] [ERROR] [host_3] [process:2616] [thread:9152] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x071A45B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-12 22:35:05,755] [ERROR] [host_1] [process:2616] [thread:7680] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x071A40D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-12 22:37:03,848] [ERROR] [host_1] [process:2616] [thread:8672] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05BE5B30>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-12 22:37:34,476] [ERROR] [host_1] [process:2616] [thread:4216] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05BF6430>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-12 22:37:38,836] [ERROR] [host_1] [process:2616] [thread:4444] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x071029B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-12 22:41:37,642] [ERROR] [host_3] [process:2616] [thread:8836] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x07A080D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 21:32:56,288] [ERROR] [host_3] [process:1144] [thread:8804] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05736110>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:10:34,007] [ERROR] [host_3] [process:1144] [thread:9128] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x057B88F0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:10:36,976] [ERROR] [host_3] [process:1144] [thread:9144] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06CDF2D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:12:09,527] [ERROR] [host_3] [process:1144] [thread:8012] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x07039D10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:12:34,362] [ERROR] [host_3] [process:1144] [thread:2128] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06D02FB0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:12:36,178] [ERROR] [host_1] [process:1144] [thread:1200] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06DA12D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:13:48,301] [ERROR] [host_1] [process:1144] [thread:6880] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058B3A90>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:14:42,577] [ERROR] [host_1] [process:1144] [thread:8580] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058B3E70>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:14:43,757] [ERROR] [host_1] [process:1144] [thread:6880] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x070394D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:21:17,949] [ERROR] [host_1] [process:1144] [thread:8712] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06CDFC70>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:22:17,896] [ERROR] [host_1] [process:1144] [thread:9012] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06DA10B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:24:09,102] [ERROR] [host_2] [process:1144] [thread:5388] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x070399B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:29:13,035] [ERROR] [host_2] [process:1144] [thread:9240] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x07039D10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:30:16,032] [ERROR] [host_2] [process:1144] [thread:9564] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06DA1430>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:32:01,438] [ERROR] [host_2] [process:1144] [thread:9464] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x098DC330>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:34:34,689] [ERROR] [host_3] [process:1144] [thread:9644] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058B38F0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:35:20,120] [ERROR] [host_2] [process:1144] [thread:7856] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05736490>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:36:46,636] [ERROR] [host_1] [process:1144] [thread:6108] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x07345D50>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:44:41,898] [ERROR] [host_3] [process:1144] [thread:6936] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06D89D90>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:44:43,448] [ERROR] [host_1] [process:1144] [thread:10100] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06D02E70>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:45:31,121] [ERROR] [host_1] [process:1144] [thread:8564] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x098DCDF0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:46:35,269] [ERROR] [host_1] [process:1144] [thread:8484] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06D89C30>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:47:55,692] [ERROR] [host_1] [process:1144] [thread:9972] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x073458B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:48:50,485] [ERROR] [host_1] [process:1144] [thread:1108] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058A55F0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:49:07,250] [ERROR] [host_2] [process:1144] [thread:9400] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x076FCF90>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:49:07,699] [ERROR] [host_3] [process:1144] [thread:7548] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x098EEE10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:56:46,479] [ERROR] [host_1] [process:1144] [thread:9188] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x098EEB10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:58:45,293] [ERROR] [host_2] [process:1144] [thread:9908] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06D02A90>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:58:45,402] [ERROR] [host_1] [process:1144] [thread:5264] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06CDFB90>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:59:44,625] [ERROR] [host_1] [process:1144] [thread:10104] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06DA12B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:59:45,063] [ERROR] [host_2] [process:1144] [thread:7856] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06D02830>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 22:59:45,366] [ERROR] [host_3] [process:1144] [thread:10132] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x057B8470>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:02:59,834] [ERROR] [host_3] [process:1144] [thread:9232] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x098DCD50>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:03:00,632] [ERROR] [host_2] [process:1144] [thread:8632] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0958D630>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:03:01,201] [ERROR] [host_1] [process:1144] [thread:6532] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0A8207D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:04:27,409] [ERROR] [host_1] [process:1144] [thread:9352] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0A820570>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:04:34,791] [ERROR] [host_1] [process:1144] [thread:4864] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058B3330>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:05:20,123] [ERROR] [host_2] [process:1144] [thread:9564] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06DA1310>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:05:21,167] [ERROR] [host_3] [process:1144] [thread:9264] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0A820CB0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:06:36,697] [ERROR] [host_2] [process:1144] [thread:5220] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x101A7870>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:07:19,368] [ERROR] [host_1] [process:1144] [thread:1304] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x076FC910>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:07:21,076] [ERROR] [host_2] [process:1144] [thread:6440] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0F9BAB10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:11:03,438] [ERROR] [host_1] [process:1144] [thread:1716] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058B3D30>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:11:33,742] [ERROR] [host_2] [process:1144] [thread:5608] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058B3A90>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:12:13,544] [ERROR] [host_2] [process:1144] [thread:10132] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x101CFFF0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:12:56,790] [ERROR] [host_3] [process:1144] [thread:8500] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x070392D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-15 23:13:51,817] [ERROR] [host_2] [process:1144] [thread:3360] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06D02ED0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-16 13:32:02,466] [ERROR] [host_3] [process:10192] [thread:11576] 本页结果未空
[2018-03-18 17:47:46,156] [ERROR] [host_3] [process:9508] [thread:12044] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05731E50>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-18 18:48:15,533] [ERROR] [host_1] [process:12184] [thread:10364] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x057ED2B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-18 18:50:12,679] [ERROR] [host_1] [process:12184] [thread:11716] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06059470>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-18 18:51:40,937] [ERROR] [command_set] [process:12184] [thread:10276] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06059E10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-18 18:57:46,879] [ERROR] [command_set] [process:9456] [thread:4968] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0582C3B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-18 18:59:39,566] [ERROR] [command_set] [process:6672] [thread:7832] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05939390>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-18 20:08:57,801] [ERROR] [host_3] [process:12220] [thread:10712] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x064D9A30>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-18 20:11:01,431] [ERROR] [host_2] [process:12220] [thread:1840] HTTPConnectionPool(host='172.29.164.92', port=8000): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0576FCB0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-18 20:40:47,399] [ERROR] [command_set] [process:11848] [thread:8564] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06355F90>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-18 20:41:17,648] [ERROR] [command_set] [process:11848] [thread:9628] HTTPConnectionPool(host='172.29.164.92', port=8002): Max retries exceeded with url: /rest/pidc/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0707B830>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-18 20:41:19,848] [ERROR] [command_set] [process:11848] [thread:9744] HTTPConnectionPool(host='172.29.164.92', port=8002): Max retries exceeded with url: /rest/pidc/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0706D570>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-18 20:44:42,428] [ERROR] [command_set] [process:11848] [thread:10284] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x06202730>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-19 10:20:56,293] [ERROR] [host_1] [process:2584] [thread:3480] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05D12710>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-19 10:23:10,388] [ERROR] [host_1] [process:2584] [thread:7156] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0601A610>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-19 10:27:22,197] [ERROR] [host_2] [process:2584] [thread:5732] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0606D070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-19 10:50:43,013] [ERROR] [host_1] [process:2584] [thread:10152] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0606D330>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-19 11:07:19,302] [ERROR] [host_1] [process:2584] [thread:8684] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0601AE30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-19 11:07:38,635] [ERROR] [host_1] [process:2584] [thread:9256] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058AE330>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-19 11:13:47,481] [ERROR] [host_1] [process:2584] [thread:7580] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x060D7CF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-19 12:00:41,567] [ERROR] [host_1] [process:1032] [thread:9460] Expecting value: line 1 column 1 (char 0)
[2018-03-19 12:00:58,397] [ERROR] [host_1] [process:1032] [thread:7080] Expecting value: line 1 column 1 (char 0)
[2018-03-19 12:01:08,580] [ERROR] [host_1] [process:1032] [thread:4284] Expecting value: line 1 column 1 (char 0)
[2018-03-19 12:01:17,462] [ERROR] [host_1] [process:1032] [thread:1056] Expecting value: line 1 column 1 (char 0)
[2018-03-19 12:01:31,771] [ERROR] [host_1] [process:1032] [thread:9680] Expecting value: line 1 column 1 (char 0)
[2018-03-19 15:44:55,041] [ERROR] [host_1] [process:8836] [thread:8964] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058680B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-19 15:45:05,243] [ERROR] [host_1] [process:8836] [thread:9240] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10&go_live=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x057E8790>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-19 15:51:24,429] [ERROR] [host_1] [process:972] [thread:8728] This QueryDict instance is immutable
[2018-03-19 15:52:12,041] [ERROR] [host_1] [process:972] [thread:7472] This QueryDict instance is immutable
[2018-03-19 15:52:58,218] [ERROR] [host_1] [process:8348] [thread:9836] "'offset'"
[2018-03-19 15:53:18,315] [ERROR] [host_1] [process:8348] [thread:3944] "'offset'"
[2018-03-19 15:57:54,620] [ERROR] [host_1] [process:8520] [thread:9364] This QueryDict instance is immutable
[2018-03-19 15:58:45,783] [ERROR] [host_1] [process:8520] [thread:6716] This QueryDict instance is immutable
[2018-03-19 15:59:14,868] [ERROR] [host_1] [process:8520] [thread:7400] This QueryDict instance is immutable
[2018-03-19 18:00:59,091] [ERROR] [host_1] [process:4640] [thread:9336] name 'offset' is not defined
[2018-03-19 18:01:18,214] [ERROR] [host_1] [process:4640] [thread:8916] name 'offset' is not defined
[2018-03-19 18:04:52,428] [ERROR] [host_1] [process:7688] [thread:9524] name 'limit' is not defined
[2018-03-19 18:06:05,747] [ERROR] [host_1] [process:7688] [thread:7644] name 'limit' is not defined
[2018-03-19 18:07:42,066] [ERROR] [host_2] [process:7444] [thread:4120] __init__() missing 1 required positional argument: 'request'
[2018-03-19 18:07:44,776] [ERROR] [host_3] [process:7444] [thread:7764] __init__() missing 1 required positional argument: 'request'
[2018-03-19 20:46:22,347] [ERROR] [host_1] [process:8316] [thread:5140] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05B32930>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-19 20:47:42,344] [ERROR] [host_1] [process:8316] [thread:9752] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05B32EB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-19 21:20:53,852] [ERROR] [host_1] [process:900] [thread:7896] ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[2018-03-19 21:23:19,306] [ERROR] [host_1] [process:900] [thread:3416] list index out of range
[2018-03-19 21:24:31,727] [ERROR] [host_1] [process:900] [thread:4124] list index out of range
[2018-03-19 21:25:42,181] [ERROR] [host_1] [process:900] [thread:7368] list index out of range
[2018-03-19 22:20:05,224] [ERROR] [host_1] [process:7424] [thread:5540] ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[2018-03-19 22:20:05,228] [ERROR] [host_1] [process:7424] [thread:4500] ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[2018-03-19 22:20:05,231] [ERROR] [host_1] [process:7424] [thread:8648] ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[2018-03-19 22:20:12,910] [ERROR] [host_1] [process:7424] [thread:9896] HTTPConnectionPool(host='127.0.0.1', port=8002): Max retries exceeded with url: /rest/host/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0972E170>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
[2018-03-20 09:41:54,768] [ERROR] [host_1] [process:7456] [thread:6084] Expecting value: line 1 column 1 (char 0)
[2018-03-20 09:41:59,483] [ERROR] [host_1] [process:7456] [thread:3004] Expecting value: line 1 column 1 (char 0)
[2018-03-20 09:42:09,756] [ERROR] [host_1] [process:7456] [thread:8540] Expecting value: line 1 column 1 (char 0)
[2018-03-20 11:15:26,287] [ERROR] [host_1] [process:4408] [thread:8500] 'str' object has no attribute 'read'
[2018-03-20 11:16:08,872] [ERROR] [host_1] [process:4408] [thread:8588] 'str' object has no attribute 'read'
[2018-03-20 11:16:23,714] [ERROR] [host_1] [process:4408] [thread:8640] Expecting value: line 1 column 1 (char 0)
[2018-03-20 13:05:44,211] [ERROR] [host_1] [process:8448] [thread:5396] the JSON object must be str, bytes or bytearray, not 'NoneType'
[2018-03-20 13:06:18,058] [ERROR] [host_1] [process:8448] [thread:8016] the JSON object must be str, bytes or bytearray, not 'NoneType'
[2018-03-20 13:07:06,005] [ERROR] [host_1] [process:8448] [thread:8112] the JSON object must be str, bytes or bytearray, not 'NoneType'
[2018-03-20 13:07:58,026] [ERROR] [host_1] [process:8448] [thread:8060] the JSON object must be str, bytes or bytearray, not 'NoneType'
[2018-03-20 13:30:29,315] [ERROR] [host_1] [process:7088] [thread:8112] Expecting value: line 1 column 1 (char 0)
[2018-03-20 13:30:38,348] [ERROR] [host_1] [process:7088] [thread:7200] Expecting value: line 1 column 1 (char 0)
[2018-03-20 14:05:33,490] [ERROR] [host_1] [process:8716] [thread:9528] list indices must be integers or slices, not str
[2018-03-20 14:06:20,017] [ERROR] [host_1] [process:8216] [thread:6680] Expecting value: line 1 column 1 (char 0)
[2018-03-20 14:08:40,324] [ERROR] [host_1] [process:8216] [thread:9908] list indices must be integers or slices, not str
[2018-03-20 14:40:04,737] [ERROR] [host_1] [process:7508] [thread:3872] list indices must be integers or slices, not str
[2018-03-20 14:41:52,796] [ERROR] [host_1] [process:7508] [thread:9340] list indices must be integers or slices, not str
[2018-03-20 15:01:57,550] [ERROR] [host_1] [process:7508] [thread:10160] list indices must be integers or slices, not str
[2018-03-20 15:03:06,899] [ERROR] [host_2] [process:7508] [thread:9120] __init__() missing 1 required positional argument: 'request'
[2018-03-20 15:06:04,906] [ERROR] [host_2] [process:8324] [thread:5544] __init__() missing 1 required positional argument: 'request'
[2018-03-20 15:36:26,697] [ERROR] [host_2] [process:9328] [thread:5984] __init__() missing 1 required positional argument: 'request'
[2018-03-20 15:36:38,584] [ERROR] [host_2] [process:9328] [thread:9256] __init__() missing 1 required positional argument: 'request'
[2018-03-20 16:50:38,803] [ERROR] [host_3] [process:10096] [thread:8720] __init__() missing 1 required positional argument: 'request'
[2018-03-20 18:24:12,809] [ERROR] [host_2] [process:1408] [thread:8304] Expecting value: line 1 column 1 (char 0)
[2018-03-20 18:28:31,470] [ERROR] [host_2] [process:1408] [thread:7504] Expecting value: line 1 column 1 (char 0)
[2018-03-20 18:31:10,776] [ERROR] [host_2] [process:1408] [thread:9744] Expecting value: line 1 column 1 (char 0)
[2018-03-20 18:35:55,903] [ERROR] [host_2] [process:9912] [thread:6264] 'list' object has no attribute 'join'
[2018-03-20 18:36:58,286] [ERROR] [host_2] [process:9912] [thread:9620] 'list' object has no attribute 'join'
[2018-03-20 18:39:43,684] [ERROR] [host_2] [process:9912] [thread:8532] 'list' object has no attribute 'join'
[2018-03-20 19:46:45,011] [ERROR] [host_3] [process:7372] [thread:4308] __init__() missing 1 required positional argument: 'request'
[2018-03-20 20:16:40,420] [ERROR] [host_2] [process:7372] [thread:9112] list indices must be integers or slices, not str
[2018-03-20 20:17:50,897] [ERROR] [host_2] [process:7372] [thread:5944] list indices must be integers or slices, not str
[2018-03-20 20:28:19,441] [ERROR] [host_3] [process:10204] [thread:10172] __init__() missing 1 required positional argument: 'request'
[2018-03-20 20:29:54,683] [ERROR] [host_2] [process:10204] [thread:2968] list indices must be integers or slices, not str
[2018-03-20 20:30:51,410] [ERROR] [host_1] [process:10204] [thread:8348] list indices must be integers or slices, not str
[2018-03-20 20:31:42,739] [ERROR] [host_2] [process:10204] [thread:8796] list indices must be integers or slices, not str
[2018-03-20 20:31:49,286] [ERROR] [host_3] [process:10204] [thread:7272] __init__() missing 1 required positional argument: 'request'
[2018-03-20 20:31:56,149] [ERROR] [host_3] [process:10204] [thread:4816] __init__() missing 1 required positional argument: 'request'
[2018-03-20 20:52:38,045] [ERROR] [host_3] [process:10272] [thread:10492] list indices must be integers or slices, not str
[2018-03-20 20:53:00,752] [ERROR] [host_2] [process:10272] [thread:9008] list indices must be integers or slices, not str
[2018-03-21 10:37:04,076] [ERROR] [host_2] [process:5404] [thread:9496] Expecting value: line 1 column 1 (char 0)
[2018-03-21 10:44:09,338] [ERROR] [host_2] [process:4408] [thread:5288] Expecting value: line 1 column 1 (char 0)
[2018-03-21 10:48:02,501] [ERROR] [host_2] [process:4408] [thread:9848] Expecting value: line 1 column 1 (char 0)
[2018-03-21 14:36:21,428] [ERROR] [command_set] [process:10664] [thread:10280] __init__() missing 1 required positional argument: 'request'
[2018-03-21 14:36:33,636] [ERROR] [command_set] [process:10664] [thread:10216] __init__() missing 1 required positional argument: 'request'
[2018-03-21 14:36:41,302] [ERROR] [command_set] [process:10664] [thread:10820] __init__() missing 1 required positional argument: 'request'
[2018-03-21 14:38:09,639] [ERROR] [command_set] [process:10664] [thread:1128] __init__() missing 1 required positional argument: 'request'
[2018-03-21 14:38:11,212] [ERROR] [command_set] [process:10664] [thread:8684] __init__() missing 1 required positional argument: 'request'
[2018-03-21 14:38:24,558] [ERROR] [command_set] [process:10664] [thread:11196] __init__() missing 1 required positional argument: 'request'
[2018-03-21 14:38:26,152] [ERROR] [command_set] [process:10664] [thread:8712] __init__() missing 1 required positional argument: 'request'
[2018-03-21 14:42:59,885] [ERROR] [command_set] [process:10664] [thread:8412] __init__() missing 1 required positional argument: 'request'
[2018-03-21 14:45:46,123] [ERROR] [command_set] [process:10664] [thread:3772] __init__() missing 1 required positional argument: 'request'
[2018-03-21 14:45:49,032] [ERROR] [command_set] [process:10664] [thread:6084] __init__() missing 1 required positional argument: 'request'
[2018-03-23 09:37:30,976] [ERROR] [command_set] [process:1136] [thread:9368] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05CA83B0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-23 09:38:52,226] [ERROR] [command_set] [process:1136] [thread:1656] HTTPConnectionPool(host='172.29.164.92', port=8001): Max retries exceeded with url: /rest/job/list/?offset=0&limit=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x058AEF30>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
[2018-03-23 12:08:37,338] [ERROR] [command_set] [process:8528] [thread:6824] 'tab'
[2018-03-23 12:11:11,187] [ERROR] [command_set] [process:8528] [thread:8564] 'tab'
[2018-03-25 18:16:20,278] [ERROR] [command_set] [process:5840] [thread:9604] '>' not supported between instances of 'str' and 'int'
[2018-03-25 18:16:47,766] [ERROR] [command_set] [process:5840] [thread:9752] '>' not supported between instances of 'str' and 'int'
[2018-03-25 18:17:23,909] [ERROR] [command_set] [process:6256] [thread:8976] 'list' object has no attribute 'get'
[2018-03-25 18:18:44,195] [ERROR] [command_set] [process:6256] [thread:10172] 'list' object has no attribute 'get'
[2018-03-25 20:03:01,946] [ERROR] [command_set] [process:8396] [thread:1732] substring not found
[2018-03-25 20:06:58,942] [ERROR] [command_set] [process:8396] [thread:10212] substring not found
[2018-03-25 20:08:35,365] [ERROR] [command_set] [process:9612] [thread:9820] 'Response' object has no attribute 'get'
[2018-03-25 20:10:21,277] [ERROR] [command_set] [process:9768] [thread:6488] 'Response' object has no attribute 'get'
[2018-03-25 20:10:39,860] [ERROR] [command_set] [process:9768] [thread:7392] 'Response' object has no attribute 'get'
[2018-03-25 20:23:07,166] [ERROR] [command_set] [process:4244] [thread:9728] 本页结果未空
[2018-03-25 21:08:59,867] [ERROR] [command_set] [process:9816] [thread:9704] This QueryDict instance is immutable
[2018-03-25 21:09:11,882] [ERROR] [command_set] [process:9816] [thread:9100] This QueryDict instance is immutable
[2018-03-25 21:10:58,886] [ERROR] [command_set] [process:9504] [thread:836] This QueryDict instance is immutable
[2018-03-25 21:11:20,951] [ERROR] [command_set] [process:6028] [thread:9348] This QueryDict instance is immutable
[2018-03-25 21:12:01,362] [ERROR] [command_set] [process:6028] [thread:9860] This QueryDict instance is immutable
[2018-03-25 21:15:02,708] [ERROR] [command_set] [process:10032] [thread:6256] 本页结果未空
[2018-03-26 11:50:27,133] [ERROR] [command_set] [process:2348] [thread:10640] Expecting value: line 1 column 1 (char 0)
[2018-03-26 11:50:29,988] [ERROR] [command_set] [process:2348] [thread:7456] Expecting value: line 1 column 1 (char 0)
[2018-03-26 11:50:33,014] [ERROR] [command_set] [process:2348] [thread:9988] Expecting value: line 1 column 1 (char 0)
[2018-03-26 11:50:35,921] [ERROR] [command_set] [process:2348] [thread:980] Expecting value: line 1 column 1 (char 0)
[2018-03-26 11:50:42,758] [ERROR] [command_set] [process:2348] [thread:8208] Expecting value: line 1 column 1 (char 0)
[2018-03-26 11:50:48,674] [ERROR] [command_set] [process:2348] [thread:9564] Expecting value: line 1 column 1 (char 0)
[2018-03-26 12:02:24,425] [ERROR] [file_manage] [process:9804] [thread:3648] 'sed' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
[2018-03-26 12:03:59,223] [ERROR] [file_manage] [process:9804] [thread:9716] 'sed' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
[2018-03-26 21:48:02,274] [ERROR] [business_attributes] [process:6532] [thread:7292] Expecting value: line 2 column 1 (char 1)
[2018-03-26 21:51:43,004] [ERROR] [business_attributes] [process:6532] [thread:7876] Expecting value: line 2 column 1 (char 1)
[2018-03-26 21:52:23,231] [ERROR] [business_attributes] [process:6532] [thread:3800] Expecting value: line 2 column 1 (char 1)
[2018-03-26 22:14:53,863] [ERROR] [business_attributes] [process:8940] [thread:8580] Expecting value: line 2 column 1 (char 1)
[2018-03-26 22:16:08,700] [ERROR] [business_attributes] [process:8940] [thread:7872] Expecting value: line 2 column 1 (char 1)
[2018-03-27 12:01:48,882] [ERROR] [business_attributes] [process:3820] [thread:9184] 'status'
[2018-03-27 12:02:30,113] [ERROR] [business_attributes] [process:3820] [thread:8396] 'status'
[2018-03-27 12:31:30,270] [ERROR] [host_1] [process:6748] [thread:5480] list indices must be integers or slices, not str
[2018-03-27 12:33:46,716] [ERROR] [host_1] [process:6748] [thread:4324] list indices must be integers or slices, not str
[2018-03-27 12:34:27,718] [ERROR] [host_1] [process:6748] [thread:1852] list indices must be integers or slices, not str
[2018-03-27 12:34:41,023] [ERROR] [host_1] [process:6748] [thread:5024] list indices must be integers or slices, not str
[2018-03-27 12:34:53,899] [ERROR] [host_1] [process:6748] [thread:8632] list indices must be integers or slices, not str
[2018-03-27 12:35:17,105] [ERROR] [host_1] [process:6748] [thread:9164] list indices must be integers or slices, not str
[2018-03-27 12:35:54,519] [ERROR] [host_1] [process:6748] [thread:8892] list indices must be integers or slices, not str
[2018-03-27 12:36:44,010] [ERROR] [host_1] [process:2656] [thread:8236] list indices must be integers or slices, not str
[2018-03-27 12:36:47,866] [ERROR] [host_1] [process:2656] [thread:1212] list indices must be integers or slices, not str
[2018-03-27 12:36:52,143] [ERROR] [host_1] [process:2656] [thread:8804] list indices must be integers or slices, not str
[2018-03-27 12:37:24,759] [ERROR] [host_1] [process:2656] [thread:9024] list indices must be integers or slices, not str
[2018-03-27 12:38:21,060] [ERROR] [host_1] [process:8964] [thread:3200] object of type 'Response' has no len()
[2018-03-27 12:38:58,104] [ERROR] [host_1] [process:8964] [thread:8128] object of type 'Response' has no len()
